FROM node:alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . .

RUN yarn install --production

ENV REACT_APP_SERVER_URL=http://192.168.64.2:80
ENV NODE_ENV=production

RUN yarn build

RUN yarn global add serve

CMD ["serve", "build"]